export const
    LOAD_STATUS = 'LOAD_STATUS',
    CHANGE_TAB = 'CHANGE_TAB',
    CHANGE_CONTENT_TYPE = 'CHANGE_CONTENT_TYPE',
    SAVE_APP_DATA = 'SAVE_APP_DATA',
    SEM_CHANGED = 'SEM_CHANGED',
    BRANCH_CHANGED = 'BRANCH_CHANGED',
    SUBJECT_CHANGED = 'SUBJECT_CHANGED',
    UPDATE_FILE_URL = 'UPDATE_FILE_URL',
    UPDATE_CIRCULAR_PDF_URL = 'UPDATE_CIRCULAR_PDF_URL',
    LOAD_LOCAL_APP_DATA = 'LOAD_LOCAL_APP_DATA',
    SET_TOKEN = 'SET_TOKEN',
    SAVE_NEWS_DATA = 'SAVE_NEWS_DATA';
