export const
    LOAD_STATUS = 'LOAD_STATUS',
    CHANGE_TAB = 'CHANGE_TAB',
    CHANGE_CONTENT_TYPE = 'CHANGE_CONTENT_TYPE',
    SAVE_APP_DATA = 'SAVE_APP_DATA',
    SAVE_NEWS_DATA = 'SAVE_NEWS_DATA';
